### PR TITLE
Moe

### PR DESCRIPTION
**Pull request by mmasiane**
Pie chart with highlighted slices

### CODE REVIEW

**Comment by tomilayo** [comment]
Maybe I am doing it wrong but when I do that, the file I am getting is the
older piechart without the highlights.

On Sun, Dec 6, 2015 at 4:43 PM, mmasiane notifications@github.com wrote:

> Closed #3 https://github.com/mauri90/vizmarktm/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mauri90/vizmarktm/pull/3#event-483816476.

## 

Thanks,

Sincerely,

Tomilayo Komolafe
Graduate Student - ISE Department

**Comment by mmasiane** [comment]
Probably my fault. I struggled to get it on there. Let me know if you are still unable to get it.
Moe.
On Dec 6, 2015 4:46 PM, tomilayo notifications@github.com wrote:Maybe I am doing it wrong but when I do that, the file I am getting is the
older piechart without the highlights.

On Sun, Dec 6, 2015 at 4:43 PM, mmasiane notifications@github.com wrote:

> Closed #3 https://github.com/mauri90/vizmarktm/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mauri90/vizmarktm/pull/3#event-483816476.

## 

Thanks,

Sincerely,

Tomilayo Komolafe
Graduate Student - ISE Department

**Comment by mmasiane** [comment]
Do you see any pull requests?
Moe.
On Dec 6, 2015 4:46 PM, tomilayo notifications@github.com wrote:Maybe I am doing it wrong but when I do that, the file I am getting is the
older piechart without the highlights.

On Sun, Dec 6, 2015 at 4:43 PM, mmasiane notifications@github.com wrote:

> Closed #3 https://github.com/mauri90/vizmarktm/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mauri90/vizmarktm/pull/3#event-483816476.

## 

Thanks,

Sincerely,

Tomilayo Komolafe
Graduate Student - ISE Department

**Comment by tomilayo** [comment]
Yes,

I received like 4 pull requests but they were all different versions of the
file but none of them were the one you showed me.

On Sun, Dec 6, 2015 at 5:18 PM, mmasiane notifications@github.com wrote:

> Do you see any pull requests?
> Moe.
> On Dec 6, 2015 4:46 PM, tomilayo notifications@github.com wrote:Maybe I
> am doing it wrong but when I do that, the file I am getting is the
> older piechart without the highlights.
> 
> On Sun, Dec 6, 2015 at 4:43 PM, mmasiane notifications@github.com
> wrote:
> 
> > Closed #3 https://github.com/mauri90/vizmarktm/pull/3.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mauri90/vizmarktm/pull/3#event-483816476.
> 
> ## 
> 
> Thanks,
> 
> Sincerely,
> 
> Tomilayo Komolafe
> Graduate Student - ISE Department
> 
> —Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mauri90/vizmarktm/pull/3#issuecomment-162353830.

## 

Thanks,

Sincerely,

Tomilayo Komolafe
Graduate Student - ISE Department

**Comment by tomilayo** [comment]
If you can send me the file directly in fact that might be easier. Or just
get on GitHub and make another file and save it up there. Because I wanted
to add some pictures from that to the report.

On Sun, Dec 6, 2015 at 5:19 PM, Tomilayo Komolafe tomilayo@vt.edu wrote:

> Yes,
> 
> I received like 4 pull requests but they were all different versions of
> the file but none of them were the one you showed me.
> 
> On Sun, Dec 6, 2015 at 5:18 PM, mmasiane notifications@github.com wrote:
> 
> > Do you see any pull requests?
> > Moe.
> > On Dec 6, 2015 4:46 PM, tomilayo notifications@github.com wrote:Maybe
> > I am doing it wrong but when I do that, the file I am getting is the
> > older piechart without the highlights.
> > 
> > On Sun, Dec 6, 2015 at 4:43 PM, mmasiane notifications@github.com
> > wrote:
> > 
> > > Closed #3 https://github.com/mauri90/vizmarktm/pull/3.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/mauri90/vizmarktm/pull/3#event-483816476.
> > 
> > ## 
> > 
> > Thanks,
> > 
> > Sincerely,
> > 
> > Tomilayo Komolafe
> > Graduate Student - ISE Department
> > 
> > —Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mauri90/vizmarktm/pull/3#issuecomment-162353830.
> 
> ## 
> 
> Thanks,
> 
> Sincerely,
> 
> Tomilayo Komolafe
> Graduate Student - ISE Department

## 

Thanks,

Sincerely,

Tomilayo Komolafe
Graduate Student - ISE Department

**Comment by mmasiane** [comment]
Will do.
Moe.
On Dec 6, 2015 5:19 PM, tomilayo notifications@github.com wrote:If you can send me the file directly in fact that might be easier. Or just
get on GitHub and make another file and save it up there. Because I wanted
to add some pictures from that to the report.

On Sun, Dec 6, 2015 at 5:19 PM, Tomilayo Komolafe tomilayo@vt.edu wrote:

> Yes,
> 
> I received like 4 pull requests but they were all different versions of
> the file but none of them were the one you showed me.
> 
> On Sun, Dec 6, 2015 at 5:18 PM, mmasiane notifications@github.com wrote:
> 
> > Do you see any pull requests?
> > Moe.
> > On Dec 6, 2015 4:46 PM, tomilayo notifications@github.com wrote:Maybe
> > I am doing it wrong but when I do that, the file I am getting is the
> > older piechart without the highlights.
> > 
> > On Sun, Dec 6, 2015 at 4:43 PM, mmasiane notifications@github.com
> > wrote:
> > 
> > > Closed #3 https://github.com/mauri90/vizmarktm/pull/3.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/mauri90/vizmarktm/pull/3#event-483816476.
> > 
> > ## 
> > 
> > Thanks,
> > 
> > Sincerely,
> > 
> > Tomilayo Komolafe
> > Graduate Student - ISE Department
> > 
> > —Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mauri90/vizmarktm/pull/3#issuecomment-162353830.
> 
> ## 
> 
> Thanks,
> 
> Sincerely,
> 
> Tomilayo Komolafe
> Graduate Student - ISE Department

## 

Thanks,

Sincerely,

Tomilayo Komolafe
Graduate Student - ISE Department

**Pull request closed without merging**
